version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI} # Added MongoDB URI
    depends_on:
      - mongo # Assuming you have a mongo service defined below

  mongo: # Added MongoDB service definition
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db # Persistent data volume for MongoDB
    restart: always # Restart MongoDB if it stops

volumes:
  mongo_data: # Definition of the persistent MongoDB data volume

